version: '3'
services:
  dind:
    image: docker:latest
    entrypoint: docker run --rm --privileged tyhjataulu/ledblinker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.hostname == raspi3
